# Forces new Travis-CI Infrastructure
sudo: false

language: php

env:
  global:
    - PHPUNIT_FLAGS=""
    - RUN_PHPCS="no"
    - USE_SCRUTINIZER="no"

matrix:
  include:
    - php: 5.5
    - php: 5.6
      env: PHPUNIT_FLAGS="--coverage-clover=coverage.clover" RUN_PHPCS="yes" USE_SCRUTINIZER="yes"
    - php: 7.0

install:
  - pear config-set auto_discover 1
  # Install Joomla coding standards
  - git clone -b phpcs-2 https://github.com/photodude/coding-standards.git $(pear config-get php_dir)/PHP/CodeSniffer/Standards/
  - git clone -b master git://github.com/squizlabs/PHP_CodeSniffer.git
  - mv $(pear config-get php_dir)/PHP/CodeSniffer/Standards/Joomla PHP_CodeSniffer/CodeSniffer/Standards/
  - phpenv rehash
  
before_script:
  # Make sure all dev dependencies are installed
  - composer selfupdate
  - composer install

script:
  - vendor/bin/phpunit --configuration phpunit.travisci.xml $PHPUNIT_FLAGS
  - if [ "$USE_SCRUTINIZER" == "yes" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;
  - if [ "$USE_SCRUTINIZER" == "yes" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;
  - if [[ $RUN_PHPCS == "yes" ]]; then cd PHP_CodeSniffer; fi
  - if [[ $RUN_PHPCS == "yes" ]]; then php scripts/phpcs -i .; fi
  - if [[ $RUN_PHPCS == "yes" ]]; then php scripts/phpcs --version .; fi
  - if [[ $RUN_PHPCS == "yes" ]]; then php scripts/phpcs --config-set show_progress 1 .; fi
  - if [[ $RUN_PHPCS == "yes" ]]; then php scripts/phpcs --config-set report_width 150 .; fi
  - if [[ $RUN_PHPCS == "yes" ]]; then php scripts/phpcs --config-set encoding utf-8 .; fi
  - if [ "$RUN_PHPCS" == "yes" ]; then php scripts/phpcs --report=full --colors -p -s --extensions=php --standard=Joomla $TRAVIS_BUILD_DIR/src/ .; fi;
